### Get all books (public)
GET http://localhost:3000/books

### Create book (protected)
# This will fail without the 'x-api-key' header
POST http://localhost:3000/books HTTP/1.1
content-type: application/json

{
  "title": "A Protected Book",
  "author": "Secret Author",
  "publication_year": 2024,
  "genre": ["Mystery"],
  "pages": 150,
  "publisher": "Private Publisher",
  "language": "English",
  "isbn": "9876543210987",
  "rating": 5.0
}

### Create book (protected, with valid API key)
# This will succeed
POST http://localhost:3000/books HTTP/1.1
content-type: application/json
x-api-key: YOUR_SECRET_API_KEY

{
  "title": "A Protected Book",
  "author": "Secret Author",
  "publication_year": 2024,
  "genre": ["Mystery"],
  "pages": 150,
  "publisher": "Private Publisher",
  "language": "English",
  "isbn": "9876543210987",
  "rating": 5.0
}